---
params:
  url: "s3_endpoint"
  accessKey: "accesskey"
  secretKey: "secretkey"
  api: "s3v4"
  path: "auto"
  preferDevice: "cuda"
  streamOperation: True
  captureDevice: 0

huggingface:
  modelName: "Ultralytics/YOLO11"
  apiToken: "apiToken"
  hfHomePath: "/tmp/"
  modelsPath: "model_checkpoints"
  filenames:
      - "yolo11x.pt"
  modelBucket: "yolo-models"
  onnxBucket: "onnx"
  modelType: "yolo"

s3:
  multipart_threshold_gb: 5
  use_thread: False
  bucket_list:
      - "yolo-models"
      - "pipelines"
      - "trainingdata"
      - "onnx"
